name: fcp-audit

services:
  fcp-audit-publisher-stub:
    ports:
      - '3005:3005'
    networks:
      - fcp-audit

  floci:
    ports:
      - '4566:4566'
    volumes:
      - floci-data:/app/data
    networks:
      - fcp-audit

  floci-init:
    networks:
      - fcp-audit

networks:
  fcp-audit:
    driver: bridge
    name: fcp-audit

volumes:
  floci-data:
